apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/MStokluska/cro-midstream?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    build.appstudio.openshift.io/build-nudge-files: "bundle-hack/update_bundle.sh"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" &&
      (".tekton/cloud-resource-operator-pull-request.yaml".pathChanged() ||
      ".tekton/cloud-resource-operator-push.yaml".pathChanged() ||
      "Containerfile.cloud-resource-operator".pathChanged() ||
      "cloud-resource-operator".pathChanged())
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: cro-midstream
    appstudio.openshift.io/component: cloud-resource-operator
    pipelines.appstudio.openshift.io/type: build
  name: cloud-resource-operator-on-push
  namespace: mstoklus-rhmi-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/redhat-user-workloads/mstoklus-rhmi-tenant/cloud-resource-operator:{{revision}}
  - name: dockerfile
    value: /Containerfile.cloud-resource-operator
  - name: path-context
    value: .
  - name: build-platforms
    value:
    - localhost
    - linux/arm64
  - name: prefetch-input
    value: '{"type": "gomod", "path": "cloud-resource-operator/"}'
  - name: hermetic
    value: "true"
  pipelineRef:
    name: build-pipeline
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'